---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
en_openfoodfacts_org_products <- read_delim("~/Downloads/en.openfoodfacts.org.products.csv",
"\t", escape_double = FALSE)
us_food <- en_openfoodfacts_org_products %>% 
  filter(countries_en=="United States")
us_food_small <- us_food %>%
  filter(creator=="usda-ndb-import")
us_food_small <- us_food_small %>%
  select(product_name, nutrition_grade_fr, pnns_groups_1, energy_100g, fat_100g, 
         `saturated-fat_100g`,`monounsaturated-fat_100g`, `polyunsaturated-fat_100g`, 
         `trans-fat_100g`,carbohydrates_100g,sugars_100g,fiber_100g,proteins_100g, 
         sodium_100g,`vitamin-c_100g`,`calcium_100g`,`iron_100g`,caffeine_100g,
         `carbon-footprint_100g`)
```

```{r}
us_food_small <- us_food_small %>%
  filter(carbohydrates_100g<100)

us_food_small <- us_food_small %>%
  filter(energy_100g<900)
```

```{r, eval=FALSE}
write_csv(us_food_small, "food_data.csv")
```