---
title: "Assignments"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

### Reading responses

For your reading responses, you are broken into three groups:

- Group A: last names starting with A-G
- Group B: last names starting with H-L
- Group C: last names starting with M-Z

Each week, one group starts the discussion off on Slack, by writing a response to the reading. Then, the other two groups *respond* to their colleagues' responses. Hopefully, this will facilitate some discussion. 

In general, your response can contain any of the following: 

- What was one thing that stood out to you? Why? 
- Can you see a connection between the readings, either a place they agree or disagree? 
- Was there a place where you disagreed with one of the authors? 
- How is what they're saying different from what you've learned in other classes? 
- Can you see a connection with another discipline or class you are in? 
- What questions do you still have?
- Find a visualization that relates to the reading and discuss that in the  context of the reading. 

### Readings

- The Functional Art, Alberto Cairo. (Introduction)
- Visualize This, Nathan Yau. (Introduction and chapter 1)

- Data Points, Nathan Yau. (Chapter 3)
- [Computational Information Design](http://benfry.com/phd/), Ben Fry (Chapters 1 and 2)

- How to Lie with Statistics, Darrell Huff (Chapters 5 and 10)
- [40 Years of Boxplots](http://vita.had.co.nz/papers/boxplots.html), Hadley Wickham, Lisa Stryjewski.
- [A brief history of the mosaic display](http://www.tandfonline.com/doi/abs/10.1198/106186002317375631), Michael Friendly 

- Elements of Graphing Data (Chapters 2 and 4), William Cleveland. 
- [Modern Crowdsoursing and Cleveland-McGill's graphical hierarchy](http://visiphilia.org/2016/08/03/CM-hierarchy), Di Cook

- The Visual Display of Quantitative Information, Edward Tufte (Chapters 4 and 6)

- Dear Data, Giorgia Lupi and Stefanie Posavec (selections)
- Raw Data: Infographic Designers' Sketchbooks, Steven Heller (selections)
- Eyeo: Converge to Inspire (selections)
- Processing, Casey Reas and Ben Fry (selections)

- How to Lie with Maps, Mark Monmonier (Chapter 3)
- Critical Questions for Big Data, danah boyd and Kate Crawford
- [Hypothetical Outcome Plots: Experiencing the Uncertain](https://medium.com/hci-design-at-uw/hypothetical-outcomes-plots-experiencing-the-uncertain-b9ea60d7c740), UW Interactive Data Lab

### Visualization in the wild

For your visualization in the wild presentations, you are going to find a visualization that you like from an outside source. You may want to look at the following websites:

- [flowingdata](http://flowingdata.com/)
- [The Upshot](https://www.nytimes.com/section/upshot)
- [fivethirtyeight](http://fivethirtyeight.com/)
- [Information is Beautiful Awards](https://www.informationisbeautifulawards.com/)
- [The Functional Art](http://www.thefunctionalart.com/)
- [stamen maps](https://hi.stamen.com/)

You will do a 2-minute presentation on your visualization, in front of the whole class. In your presentation, you will need to describe what the visualization shows, and highlight one design decision you like. This is a very short presentation, so I want it to be low-stakes. 

### Final project

#### Places to look for data

For the final project, you will need to find (or generate) some data. Below is a list of places to get started looking for data. Remember, you may need to do some data manipulation in order to get the data into a form that works for your project (e.g. using pivot tables in Google Sheets) and you can ask me or the Data Assistants for assistance. 

- Data is Plural [tinyletter](https://tinyletter.com/data-is-plural) and associated [spreadsheet](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0)

- FiveThirtyEight [data archive](https://github.com/fivethirtyeight/data)

- [Data.gov](https://www.data.gov/) 186,000+ datasets!

- [Social Explorer](http://www.socialexplorer.com/) is a great interface to Census and American Community Survey data (much more user-friendly than the official government sites). Smith has a site license, but you may need to create an account. 

- [Gallup Analytics](http://libguides.smith.edu/az.php?a=g) (available through the library databases)

- [Data and Story Library](http://dasl.datadesk.com/) (DASL). (This, and [more](http://it.stlawu.edu/~rlock/) ideas from Robin Lock.)

- Jo Hardin at Pomona College has a [nice list](http://research.pomona.edu/johardin/datasources/) of data sources on her website. 

-   U.S. [Bureau of Labor Statistics](http://www.bls.gov/) 

-   U.S. [Census Bureau](http://www.census.gov)

-   [Gapminder](https://www.gapminder.org/data/), data about the world. 

- IRE and NICAR are good resources for the types of data journalists care about. For example, [Energy data sources](https://github.com/InsideEnergy/24-energy-stories-CAR16) and [Chrys Wu's resource page](http://blog.chryswu.com/2016/03/08/nicar16-slides-links-tutorials-resources/). 

-   Nathan Yau's (old) [guide to finding data on the internet](http://flowingdata.com/2009/10/01/30-resources-to-find-the-data-you-need/)


#### Idea
The first milestone for your final project is a short (several sentence) description of your concept for the final project. It should include:

- your name, and the name of any group members (if applicable)
- the data you are planning to visualize, and the question(s) you will try to answer
- the tool you are planning to use (Plotly, hand-drawn, voyant-tools.org, R, etc)
- the visual representation(s) you are thinking of using (e.g. map, word cloud, bar chart, scatterplot, etc)

You should submit this information as a PDF document [on moodle](https://moodle.smith.edu/mod/assign/view.php?id=266953). (If you are using Microsoft Word to produce the document, please Print To or Export To PDF.)

#### "Poster" presentation

During the poster session, you will present your visualization(s). If they are interactive (like Plotly) you may want to demo using your laptop. If you have produced something static, particularly if it was done by hand, you may have a physical artifact. This can be a paper printout or other physical item. You do *not* have to produce a standard "poster" for the demo session. 

#### Writeup

By the last day of the semester (Dec 22), you will turn in a final version of your visualization(s), along with a writeup about the design decisions you made. This may include decisions about:

- encoding
- color
- plot types
- data filtering/aggregation/pivot tables
- interactive elements
- etc

I would like these decisions to be backed up with citations to relevant literature. You can draw on the material we read throughout the semester, as well as material referred to in the lectures. 

You should also explain where your data came from, and any data processing you have completed. If you did data processing in something reproducible (like R) you could submit code as part of this documentation. If you did work in spreadsheets, please describe in words what you did. For example, "I filtered the data to only include 2009, and then I used a pivot table to summarize by group before importing into Plotly."

Your writeup should be at least 3 pages long, and include a bibliography. It is okay (even encouraged!) to include screenshots of your work or of inspirational materials, but those images will not count toward the page length. 
