---
title: "Schedule"
---

Date | Topic | Lab | 
-----|----------------------|---------------------|
9/11 | [Introduction to data visualization](01_CommunicatingWithData.pdf) | |
9/13 | [Visualization fundamentals pt. 1](02_VisualizationFundamentals.pdf) | |
9/18 |  | [Getting started in Plotly](03_IntroductionToPlotly.pdf) | 
9/20 | **No class** | |
9/25 | [Visualization fundamentals pt. 2](04_GestaltAndBarcharts.pdf) | | 
9/27 | | [Visualizing one variable](05_Aggregation.pdf) ([data](https://docs.google.com/a/smith.edu/spreadsheets/d/1fhMYD__IiBd6uxdF-s0NZUsb61ilLX0Tm_CqMX4eg2A/edit?usp=sharing)) | 
10/2 | |  [Visualizing two variables](06_filtering.pdf) ([data](https://docs.google.com/a/smith.edu/spreadsheets/d/1blEcuuc_L_g_q7fYZ3w7dScxFy_4f58rreQ4NsSHJuE/edit?usp=sharing)) |
10/4 | [Color theory](07_color.pdf) |  | 
10/9  |  **Autumn recess**      |  |
10/11 | [Graphical perception](08_perception.pdf) | | 
10/16 |  [Design principles](09_principles.pdf) | Mini-lab |  
10/18 | [Artistic visualization](10_art.pdf) | Hand-drawn viz [data](https://docs.google.com/a/smith.edu/spreadsheets/d/1PnJ8_nmE827Vf-QtDaMC7r91oIYjC1C3ETDyJ1S0Dd8/edit?usp=sharing) |
10/23 | Museum and special collections visit | |
10/25 |  Museum and special collections visit | | 
10/30 |  [Visualization of higher-dimensional data](11_multidimensional.pdf) | Pairs plots and 3D viz ([data](college.csv)) |
11/1  | [Spatial data](12_spatial.pdf) | Maps ([data](who.csv)) |
11/6  | [Visualizing uncertainty](13_uncertainty.pdf)  | |
11/8  |  Narrative  | |
11/13 | | **Final project workshop 1**  |
11/15 | **Visualization in the wild presentations** | |
11/20 | **Visualization in the wild presentations** | |
11/22 | **Thanksgiving recess** | |
11/27 | [Text Data](14_text.pdf)  | Text visualization |
11/29 |Interactivity, iteration, and animation | Interactivity |
12/4  | TBD | |
12/6  | | **Final project workshop 2**  |
12/11 | What next? ||
12/13 | **Project Presentations** ||
